Домашнее задание №11 «Клиент TELNET»
and67o/otus_hw pull request #12
Opened 2020-12-27 10:55 UTC by and67o

## Домашнее задание №11 «Клиент TELNET»

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены юнит-тесты - до 2 баллов
- [ ] Понятность и чистота кода - до 4 баллов

#### Зачёт от 7 баллов

2020-12-29 16:04 UTC, balabanovds requested changes
Спасибо за работу.

Есть замечания критического характера:
- не реализован обработка `Ctrl+D` и вывод сообщения
- неправильно обрабатываются аргументы

Не написаны unit-тесты, а это минус 2 балла.
Также есть незначительные комментарии рекомендательного характера.

Если будут вопросы - обращайтесь в Slack
Успехов!

https://otus.ru/teacher-lk/homework/85678/8092/

2020-12-29 16:04 UTC, balabanovds commented on hw11_telnet_client/main.go
> +	if len(args) != 4 {
если запустить без флага timeout, ожидая использование дефолта то программа завершится

2020-12-29 16:04 UTC, balabanovds commented on hw11_telnet_client/main.go
> +	ctx, cancel := context.WithCancel(bcg)
лучше просто `context.WithCancel(context.Background())`

2020-12-29 16:04 UTC, balabanovds commented on hw11_telnet_client/main.go
> +		close(signalsChan)
можно не закрывать канал, он будет собран GC. 
закрывать канал имеет смысл когда кто-то ожидает закрытие канала

2020-12-29 16:04 UTC, balabanovds commented on hw11_telnet_client/main.go
> +		err := client.Close()
дело вкуса, но можно сократить на одну строчку
```go
if err := client.Close(); err != nil {
//...
}
```

2021-01-16 18:24 UTC, and67o commented on hw11_telnet_client/main.go
> +	if len(args) != 4 {
исправил

2021-01-16 18:24 UTC, and67o commented on hw11_telnet_client/main.go
> +	ctx, cancel := context.WithCancel(bcg)
я убрал вообще контекст

2021-01-16 18:25 UTC, and67o commented on hw11_telnet_client/main.go
> +		close(signalsChan)
исправил

2021-01-18 04:45 UTC, balabanovds approved these changes
Спасибо за исправления.

Есть некоторые предложения по стилю кода.
Также отмечу, что не написаны unit-тесты и сообщение, которое выводится выглядит так: `error:%!s(<nil>)`

Оценка: 7/10

Если будут вопросы -  доступен в Slack.

2021-01-18 04:45 UTC, balabanovds commented on hw11_telnet_client/main.go
> +	if (len(args) > maxArgs) || (len(args) < minArgs) {
Можно проще - `flag.NArgs`

2021-01-18 04:45 UTC, balabanovds commented on hw11_telnet_client/main.go
> +		signal.Stop(signalsChan)
Лучше все же в `defer`, чтобы канал обрабатывался в любом случае

2021-01-18 04:45 UTC, balabanovds commented on hw11_telnet_client/main.go
> +func receive(client TelnetClient, errorsChan chan error) {
Можно сделать код более лаконичным, если использовать анонимную функцию.
Ведь `client.Send` и `client.Receive` имеют одинаковую сигнатуру..

2021-01-19 14:57 UTC, merged