Домашнее задание №3 «Частотный анализ»
and67o/otus_hw pull request #3
Opened 2020-09-22 20:23 UTC by and67o

## Домашнее задание №3 «Частотный анализ»

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены новые юнит-тесты - до 4 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2020-09-23 06:58 UTC, Antonboom requested changes
https://otus.ru/teacher-lk/homework/85678/8376/

Здравствуйте!
Хорошая декомпозиция на подпрограммы.

Не хватает новых тестов (см. критерии оценки).
Предварительно
5 / 10

2020-09-23 06:58 UTC, Antonboom commented on hw03_frequency_analysis/top_test.go
> +			fmt.Println( Top10(text), expected)
результат можно выводить с помощью доп. аргументов `require.*`

2020-09-23 06:58 UTC, Antonboom commented on hw03_frequency_analysis/top_test.go
> +	"fmt"
Где новые тесты?

2020-09-23 06:58 UTC, Antonboom commented on hw03_frequency_analysis/top.go
> +	space := regexp.MustCompile(`\s+`)
регулярку стоит компилировать заранее (в var, например) + Must-функции могут паниковать, что для уровня функции не есть гуд, но норм для уровня пакета

2020-09-23 06:58 UTC, Antonboom commented on hw03_frequency_analysis/top.go
> +func handleText(text string) string {
слишком общее название, я бы сделал функцию-получалку слов и объединил этот код со Split

2020-09-23 06:58 UTC, Antonboom commented on hw03_frequency_analysis/top.go
> +		if len(res) == 10 {
не используется MaxWords

да и в целом я бы сюда внёс ифку с 24 строки

2020-09-24 19:56 UTC, and67o commented on hw03_frequency_analysis/top_test.go
> +			fmt.Println( Top10(text), expected)
убрал вообще

2020-09-24 19:57 UTC, and67o commented on hw03_frequency_analysis/top_test.go
> +	"fmt"
добавил тесты

2020-09-24 19:57 UTC, and67o commented on hw03_frequency_analysis/top.go
> +	space := regexp.MustCompile(`\s+`)
вынес в var

2020-09-24 19:57 UTC, and67o commented on hw03_frequency_analysis/top.go
> +func handleText(text string) string {
исправил

2020-09-24 19:58 UTC, and67o commented on hw03_frequency_analysis/top.go
> +		if len(res) == 10 {
исправил. строку перенес

2020-09-25 04:56 UTC, Antonboom approved these changes

2020-09-25 04:57 UTC, Antonboom approved these changes, later dismissed
Отлично!

Можно использовать `SliceStable` для сохранение порядка элементов, у которых одинаковое количество встречаемости.

Принято
10 / 10

2020-09-26 12:26 UTC, Antonboom approved these changes

2020-10-11 18:44 UTC, merged