Домашнее задание №4 «LRU-кэш
and67o/otus_hw pull request #5
Opened 2020-10-13 07:40 UTC by and67o

## Домашнее задание №4 «LRU-кэш»

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены новые юнит-тесты для списка - 1 балл
- [ ] Добавлены новые юнит-тесты для кэша (включая тест на логику
выталкивания из кэша редко используемых элементов) - до 3 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2020-10-17 17:05 UTC, Antonboom requested changes
https://otus.ru/teacher-lk/homework/85678/8087/

Здравствуйте!

Отличная, аккуратная работа.
Но не хватает тестов (см. ТЗ и критерии оценки).

Предварительно
5 / 10

2020-10-17 17:05 UTC, Antonboom commented on hw04_lru_cache/cache.go
> +func (l *lruCache) Delete() bool {
я бы предложил скорее `purge` или что-нибудь а ля "очистка".
delete больше про удаление чего-то конкретного

\+ это выглядит как приватный метод

2020-10-17 17:05 UTC, Antonboom commented on hw04_lru_cache/cache.go
> +	for key, ok := range l.items {
O(n)

предложил бы вызвать перезатирание новыми объектами по аналогии с конструктором (привет GC)

2020-10-18 20:42 UTC, and67o commented on hw04_lru_cache/cache.go
> +func (l *lruCache) Delete() bool {
переименовал на purge и сделал приватным

2020-10-18 20:42 UTC, and67o commented on hw04_lru_cache/cache.go
> +	for key, ok := range l.items {
исправил

2020-10-19 16:13 UTC, Antonboom submitted a review, later dismissed
Тесты на список отсутствуют.
В тестах на кэш отсутствует главный (см. алгоритм тестирования в ТЗ).

Принято
7 / 19

2020-10-31 10:06 UTC, and67o commented
Добавил тесты

2020-11-07 07:17 UTC, Antonboom approved these changes
10 / 10

2020-11-07 09:20 UTC, merged